'use client';

import Image from 'next/image';
import { AnimatePresence, motion, useMotionTemplate, useMotionValue, useScroll, useSpring, useTransform } from 'framer-motion';
import { ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, Check, Film, Globe2, Instagram, Menu, MonitorPlay, Play, ShieldCheck, Sparkles, Target, X, Zap } from 'lucide-react';
import { MouseEvent, useEffect, useRef, useState } from 'react';

const metrics = [
  { value: '500K+*', label: 'Combined community', note: 'Across our core social channels' },
  { value: '20M+*', label: 'Monthly views', note: 'Short-form filmmaking content' },
  { value: '6.8%*', label: 'Engagement rate', note: 'Average community interaction' },
  { value: '65M+*', label: 'Annual reach', note: 'Filmmakers and creators worldwide' },
];

const formats = [
  { icon: MonitorPlay, n: '01', title: 'Promotional video share', text: 'Your approved campaign video distributed to our filmmaking audience with clear positioning and a direct CTA.', tags: ['Instagram Reel', 'Facebook', 'Pinned comment'] },
  { icon: Film, n: '02', title: 'Custom content creation', text: 'A dedicated short-form concept created around your product, feature, workflow or filmmaker use case.', tags: ['Concept', 'Production', 'Cross-platform'] },
  { icon: Sparkles, n: '03', title: 'Product integration', text: 'Your tool is introduced naturally inside useful filmmaking content instead of appearing as a disconnected ad.', tags: ['Native mention', 'Workflow demo', 'Brand CTA'] },
  { icon: Target, n: '04', title: 'Long-term sponsorship', text: 'A consistent campaign system with recurring content, priority placement and stronger brand association over time.', tags: ['Recurring posts', 'Link placement', 'Custom plan'] },
];

const packages = [
  { label: 'FASTEST LAUNCH', title: 'Promotional Video Share', price: '$300', text: 'Best for brands with a finished campaign asset that already fits the filmmaking audience.', features: ['Distribution across agreed TFM channels', 'Caption adapted for our community', 'Brand tag and campaign CTA', 'Pinned comment when agreed', 'Basic performance summary'], cta: 'Book a promotional share' },
  { label: 'MOST POPULAR', title: 'Custom Content Creation', price: '$600', text: 'Best for products that need a native, educational story designed for filmmakers.', features: ['Campaign concept and creative direction', 'Custom short-form production', 'Product demonstration or workflow use case', 'Cross-platform publishing plan', 'Campaign performance report'], cta: 'Start a custom campaign', featured: true },
];

const reveal = { hidden: { opacity: 0, y: 54 }, show: { opacity: 1, y: 0, transition: { duration: .9, ease: [0.16, 1, 0.3, 1] } } };

function MagneticLink({ children, href, className = '' }: { children: React.ReactNode; href: string; className?: string }) {
  const x = useMotionValue(0), y = useMotionValue(0);
  const sx = useSpring(x, { stiffness: 190, damping: 17 }), sy = useSpring(y, { stiffness: 190, damping: 17 });
  const move = (e: MouseEvent<HTMLAnchorElement>) => { const r = e.currentTarget.getBoundingClientRect(); x.set((e.clientX - r.left - r.width / 2) * .16); y.set((e.clientY - r.top - r.height / 2) * .16); };
  return <motion.a href={href} className={className} style={{ x: sx, y: sy }} onMouseMove={move} onMouseLeave={() => { x.set(0); y.set(0); }}>{children}</motion.a>;
}

export default function Home() {
  const [open, setOpen] = useState(false), [loaded, setLoaded] = useState(false);
  const heroRef = useRef<HTMLElement>(null);
  useEffect(() => { const timer = setTimeout(() => setLoaded(true), 1550); return () => clearTimeout(timer); }, []);
  const mouseX = useMotionValue(50), mouseY = useMotionValue(50);
  const glow = useMotionTemplate`radial-gradient(680px circle at ${mouseX}% ${mouseY}%, rgba(245,201,0,.16), transparent 62%)`;
  const { scrollYProgress } = useScroll();
  const { scrollYProgress: heroProgress } = useScroll({ target: heroRef, offset: ['start start', 'end start'] });
  const heroY = useTransform(heroProgress, [0, 1], ['0%', '14%']);
  const heroScale = useTransform(heroProgress, [0, 1], [1, 1.08]);
  const heroOpacity = useTransform(heroProgress, [0, .85], [1, .15]);
  const navItems = [['Audience', '#audience'], ['Formats', '#formats'], ['Results', '#results'], ['Packages', '#packages']];

  return <main onMouseMove={(event) => { mouseX.set((event.clientX / window.innerWidth) * 100); mouseY.set((event.clientY / window.innerHeight) * 100); }}>
    <AnimatePresence>{!loaded && <motion.div className="loader" exit={{ y: '-100%' }} transition={{ duration: .8, ease: [.76, 0, .24, 1] }}><Image src="/logo.svg" width={220} height={92} alt="Today Film Makers" /><div className="loaderLine"><motion.i initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ duration: 1.1, ease: [.16, 1, .3, 1] }} /></div><p>BUILDING THE CAMPAIGN FRAME</p></motion.div>}</AnimatePresence>
    <div className="grain" /><motion.div className="ambientGlow" style={{ background: glow }} /><motion.div className="progress" style={{ scaleX: scrollYProgress }} />

    <header className="nav"><a className="brand" href="#top"><Image src="/logo.svg" width={90} height={40} alt="Today Film Makers" /></a><nav>{navItems.map(([label, href]) => <a key={label} href={href}>{label}</a>)}</nav><MagneticLink className="navCta" href="/contact">Partner with us <ArrowUpRight size={15} /></MagneticLink><button className="menu" onClick={() => setOpen(!open)} aria-label="Menu">{open ? <X /> : <Menu />}</button></header>
    {open && <motion.div className="mobileNav" initial={{ clipPath: 'inset(0 0 100% 0)' }} animate={{ clipPath: 'inset(0 0 0 0)' }}>{navItems.map(([label, href], i) => <motion.a key={label} href={href} initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * .06 }} onClick={() => setOpen(false)}><span>0{i + 1}</span>{label}<ArrowUpRight /></motion.a>)}<a href="/contact"><span>05</span>Contact<ArrowUpRight /></a></motion.div>}

    <motion.section className="dealHero" id="top" ref={heroRef} style={{ opacity: heroOpacity }}>
      <motion.div className="dealHeroBackdrop" style={{ y: heroY, scale: heroScale }}><Image fill priority src="https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=2400&q=90" alt="Filmmaking audience" /><div className="dealShade" /></motion.div>
      <div className="heroGridLine" />
      <div className="dealHeroCopy"><motion.span initial={{ opacity: 0, y: 18 }} animate={loaded ? { opacity: 1, y: 0 } : {}} transition={{ delay: .1 }}>MEDIA KIT · FILMMAKING & CREATIVE BRANDS</motion.span><h1><motion.b initial={{ y: '110%' }} animate={loaded ? { y: 0 } : {}} transition={{ duration: .9, delay: .12, ease: [.16, 1, .3, 1] }}>WHERE BRANDS</motion.b><br /><motion.em initial={{ y: '110%' }} animate={loaded ? { y: 0 } : {}} transition={{ duration: .9, delay: .22, ease: [.16, 1, .3, 1] }}>MEET FILMMAKERS.</motion.em></h1><p>Today Film Makers gives filmmaking, camera, editing, AI and creative-technology brands direct access to a focused community through native short-form campaigns.</p><div className="heroActions"><MagneticLink href="/contact" className="primaryAction">Start a campaign <ArrowRight size={16} /></MagneticLink><a href="#audience" className="secondaryAction">View audience <ArrowDownRight size={16} /></a></div></div>
      <motion.div className="heroMediaCard" initial={{ opacity: 0, x: 60, rotate: 3 }} animate={loaded ? { opacity: 1, x: 0, rotate: 0 } : {}} transition={{ duration: 1, delay: .35, ease: [.16, 1, .3, 1] }}><div className="mediaCardTop"><span>TFM CAMPAIGN PREVIEW</span><span>9:16</span></div><div className="mediaCardImage"><Image fill src="https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=90" alt="Camera campaign preview" /><button aria-label="Play preview"><Play fill="currentColor" /></button></div><div className="mediaCardBottom"><span>Creative technology</span><strong>Built for the filmmaking feed.</strong></div><motion.div className="floatingMetric fmOne" animate={{ y: [0, -8, 0] }} transition={{ duration: 4, repeat: Infinity }}><small>MONTHLY VIEWS*</small><b>20M+</b></motion.div><motion.div className="floatingMetric fmTwo" animate={{ y: [0, 8, 0] }} transition={{ duration: 4.6, repeat: Infinity }}><small>COMMUNITY*</small><b>500K+</b></motion.div></motion.div>
      <div className="demoFlag">* DEMO METRICS — REPLACE WITH VERIFIED TFM INSIGHTS BEFORE PUBLIC LAUNCH</div>
    </motion.section>

    <section className="brandTicker"><div>CAMERAS <i>+</i> EDITING SOFTWARE <i>+</i> AI TOOLS <i>+</i> LIGHTING <i>+</i> AUDIO <i>+</i> CREATIVE TECHNOLOGY <i>+</i> CAMERAS <i>+</i> EDITING SOFTWARE <i>+</i> AI TOOLS <i>+</i></div></section>

    <section className="audienceSection" id="audience"><div className="pageShell"><motion.div className="sectionIntro" initial="hidden" whileInView="show" viewport={{ once: true, amount: .2 }} variants={reveal}><span className="eyebrow">01 — THE AUDIENCE</span><h2>A focused creative community<br />built for <i>relevant brands.</i></h2><p>Our audience follows Today Film Makers to discover filmmaking techniques, tools, workflows and creative inspiration. That creates a natural environment for product education and brand discovery.</p></motion.div><div className="metricGrid">{metrics.map((metric, i) => <motion.article key={metric.label} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .07 }}><span>0{i + 1}</span><strong>{metric.value}</strong><h3>{metric.label}</h3><p>{metric.note}</p></motion.article>)}</div><div className="analyticsGrid"><article className="analyticsPanel agePanel"><div className="panelHeader"><span>Age breakdown*</span><small>Sample layout data</small></div>{[['18–24', '31%'], ['25–34', '45%'], ['35–44', '17%'], ['45+', '7%']].map(([age, value]) => <div className="barRow" key={age}><span>{age}</span><div><i style={{ width: value }} /></div><b>{value}</b></div>)}</article><article className="analyticsPanel"><div className="panelHeader"><span>Platform mix*</span><small>Sample layout data</small></div><div className="platformSplit"><div><Instagram /><strong>64%</strong><span>Instagram</span></div><div><Globe2 /><strong>36%</strong><span>Facebook & others</span></div></div></article><article className="analyticsPanel interestPanel"><div className="panelHeader"><span>Audience interests</span><small>High-intent creative categories</small></div><div className="interestTags">{['Filmmaking', 'Cinematography', 'Video editing', 'Camera gear', 'Lighting', 'AI tools', 'Sound', 'VFX'].map(x => <span key={x}>{x}</span>)}</div></article><article className="analyticsPanel geoPanel"><div className="panelHeader"><span>Global audience*</span><small>Sample layout data</small></div><div className="geoNumber">100+<small>countries reached</small></div><p>Primary creative markets can be displayed here after the verified insights are provided.</p></article></div></div></section>

    <section className="formatsSection" id="formats"><div className="pageShell"><div className="sectionIntro compact"><span className="eyebrow">02 — CONTENT FORMATS</span><h2>Campaigns designed to be<br /><i>seen, saved and remembered.</i></h2><p>Each collaboration is adapted to the product, campaign goal and audience behavior—not forced into one generic format.</p></div><div className="formatCards">{formats.map((format) => { const Icon = format.icon; return <motion.article key={format.n} initial="hidden" whileInView="show" viewport={{ once: true, amount: .25 }} variants={reveal}><div><span>{format.n}</span><Icon /></div><h3>{format.title}</h3><p>{format.text}</p><div className="tagRow">{format.tags.map(tag => <span key={tag}>{tag}</span>)}</div><ArrowUpRight className="formatArrow" /></motion.article>; })}</div></div></section>

    <section className="resultsSection" id="results"><div className="pageShell"><div className="sectionIntro compact light"><span className="eyebrow">03 — CAMPAIGN PROOF</span><h2>Built to make creative products<br /><i>look valuable.</i></h2><p>This sample campaign block will become a real TFM case study once you provide the final post, screenshots and performance insights.</p></div><div className="caseStudy"><div className="caseVisual"><Image fill src="https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=1800&q=90" alt="Sample creative campaign" /><div className="caseOverlay"><span>SAMPLE CAMPAIGN 001</span><button aria-label="Play campaign"><Play fill="currentColor" /></button></div></div><div className="caseContent"><span className="eyebrow">CREATIVE SOFTWARE LAUNCH · DEMO</span><h3>Turning one product feature into a clear filmmaker use case.</h3><p>The campaign introduces the tool through a visual workflow, demonstrates the result and gives the audience a direct reason to explore it.</p><div className="caseMetrics">{[['1.35M*', 'Views'], ['863K*', 'Reach'], ['47K*', 'Interactions'], ['28%*', 'Non-followers']].map(x => <div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div><small>* Placeholder campaign data for presentation only.</small></div></div></div></section>

    <section className="whySection"><div className="pageShell"><div className="centerIntro"><span className="eyebrow">WHY PARTNER WITH TFM</span><h2>We make brand content feel<br /><i>native to the community.</i></h2></div><div className="whyGrid"><article><ShieldCheck /><h3>Trusted context</h3><p>Your product appears inside a filmmaking environment the audience already chooses to follow.</p></article><article><Zap /><h3>Clear creative angle</h3><p>We translate product features into a result, workflow or benefit filmmakers understand immediately.</p></article><article><BarChart3 /><h3>Campaign reporting</h3><p>Once real data is supplied, every collaboration can be supported with clear performance metrics.</p></article></div></div></section>

    <section className="packagesSection" id="packages"><div className="pageShell"><div className="centerIntro"><span className="eyebrow">04 — COLLABORATION OPTIONS</span><h2>Choose the format that fits<br /><i>your campaign.</i></h2><p>Final pricing can change depending on scope, usage rights, production requirements and campaign duration.</p></div><div className="packageGrid">{packages.map((pack) => <article className={pack.featured ? 'packageCard featured' : 'packageCard'} key={pack.title}>{pack.featured && <span className="popular">MOST POPULAR</span>}<span className="packageLabel">{pack.label}</span><h3>{pack.title}</h3><div className="price"><small>Starting at</small><strong>{pack.price}</strong></div><p>{pack.text}</p><div className="packageTags"><span>FILMMAKING</span><span>CREATIVE TECH</span><span>SOCIAL</span></div><ul>{pack.features.map(item => <li key={item}><Check />{item}</li>)}</ul><a href="/contact">{pack.cta}<ArrowRight /></a></article>)}</div><div className="customPackage"><div><span>CUSTOM PARTNERSHIP</span><h3>Need a long-term campaign or a custom deliverable mix?</h3><p>We can build a tailored partnership around recurring posts, sponsorship placement, usage rights and multi-platform distribution.</p></div><a href="/contact">Request a campaign quote <ArrowUpRight /></a></div></div></section>

    <section className="processSection"><div className="pageShell"><div className="sectionIntro compact"><span className="eyebrow">05 — HOW IT WORKS</span><h2>One clear process.<br /><i>No campaign chaos.</i></h2></div><div className="processRail">{[['01', 'Brief', 'You share the product, objective, audience and required deliverables.'], ['02', 'Creative direction', 'We define the strongest format and product angle for the TFM audience.'], ['03', 'Production & approval', 'The asset is prepared, reviewed and approved before publishing.'], ['04', 'Publish & report', 'The campaign goes live and performance is shared after the agreed period.']].map(step => <article key={step[0]}><span>{step[0]}</span><h3>{step[1]}</h3><p>{step[2]}</p></article>)}</div></div></section>

    <section className="finalDealCta"><div><span className="eyebrow">START A BRAND PARTNERSHIP</span><h2>Tell us about<br /><i>your campaign.</i></h2><p>Share your product, campaign goal and preferred collaboration format. We&apos;ll reply with the next steps.</p><MagneticLink href="/contact" className="ctaCircle">OPEN CONTACT PAGE <ArrowUpRight /></MagneticLink></div></section>

    <footer><div className="footerTop"><Image src="/logo.svg" alt="Today Film Makers" width={128} height={58} /><div><span>BRAND PARTNERSHIPS</span><h2>MAKE THE NEXT<br />FRAME COUNT.</h2></div></div><div className="footerBottom"><span>© 2026 TODAY FILM MAKERS</span><div><a href="#audience">AUDIENCE</a><a href="#packages">PACKAGES</a><a href="/contact">CONTACT</a></div><a href="#top">BACK TO TOP ↑</a></div></footer>
  </main>;
}
